name: Arm Build

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:

  thumbv7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose
      - name: Build Debug
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

  thumbv6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose
      - name: Build Debug
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features thumbv6
      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features thumbv6
